# Generated by Django 5.2.4 on 2025-07-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trpg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_plot_point_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='player_state',
            field=models.JSONField(default=dict),
        ),
    ]
